//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input correct email..
        /// </summary>
        internal static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FailLogin {
            get {
                return ResourceManager.GetString("FailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail during search of contact..
        /// </summary>
        internal static string FindContactFail {
            get {
                return ResourceManager.GetString("FindContactFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts have been found..
        /// </summary>
        internal static string FindContactSuccess {
            get {
                return ResourceManager.GetString("FindContactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no contact with such last name in book yet..
        /// </summary>
        internal static string FindNone {
            get {
                return ResourceManager.GetString("FindNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail during reading of contacts..
        /// </summary>
        internal static string GetAllContactFail {
            get {
                return ResourceManager.GetString("GetAllContactFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not contacts in book yet..
        /// </summary>
        internal static string GetAllNone {
            get {
                return ResourceManager.GetString("GetAllNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull read all contacts..
        /// </summary>
        internal static string GetAllSuccess {
            get {
                return ResourceManager.GetString("GetAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail during reading detail about contact..
        /// </summary>
        internal static string GetDetailsFail {
            get {
                return ResourceManager.GetString("GetDetailsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull read detail about contact..
        /// </summary>
        internal static string GetDetailsSuccess {
            get {
                return ResourceManager.GetString("GetDetailsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create password which contain minimum 1 digit and 1 letter. Password should be minimum 8 characters..
        /// </summary>
        internal static string PasswordReq {
            get {
                return ResourceManager.GetString("PasswordReq", resourceCulture);
            }
        }
    }
}
